# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-18 17:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('idphoto', models.IntegerField(primary_key=True, serialize=False)),
                ('likes', models.IntegerField()),
                ('coments', models.IntegerField()),
                ('hastags', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('followers', models.IntegerField()),
                ('follows', models.IntegerField()),
                ('facebook_vinculado', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Users',
        ),
        migrations.AddField(
            model_name='photos',
            name='username_vinculed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crawler.User'),
        ),
    ]
