# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-18 19:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0003_followrelation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photos',
            old_name='coments',
            new_name='comments',
        ),
        migrations.RenameField(
            model_name='photos',
            old_name='username_vinculed',
            new_name='owner',
        ),
        migrations.RemoveField(
            model_name='photos',
            name='hastags',
        ),
        migrations.RemoveField(
            model_name='user',
            name='facebook_vinculado',
        ),
        migrations.AddField(
            model_name='photos',
            name='hashtags',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='crawler',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='user',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='external_link',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='user',
            name='facebook_link',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_pic_link',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='followers',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='follows',
            field=models.IntegerField(default=0),
        ),
    ]
