# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-18 21:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0005_user_scraped'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='parsed',
            field=models.BooleanField(default=False),
        ),
    ]
